import { loadMenu } from '../menu.js';
import bangers from '../images/bangers.png';
import kidney from '../images/kidney.png';
import pea from '../images/pea.png';
import yorkshire from '../images/yorkshire.png';
import shepherd from '../images/shepherd.png';
import toad from '../images/toad.png';

export const loadDishes = () => {
    const container = document.querySelector(".container");
    while (container.lastElementChild) {
      container.removeChild(container.lastElementChild);
    }
    const main = document.createElement("div");
    main.classList.add("main");
    container.appendChild(main);
    const header = document.createElement("h2");
    header.textContent = "Signature Dishes";
    main.appendChild(header);

    const card1 = document.createElement("div");
    const info1 = document.createElement("div");
    card1.classList.add("card");
    info1.classList.add("info");
    const image1 = document.createElement("img");
    image1.src = bangers;
    image1.classList.add("menu-img");
    image1.setAttribute("alt", "Picture of bangers and mash");
    card1.appendChild(image1);
    card1.appendChild(info1);
    const head1 = document.createElement("h3");
    head1.textContent = "Bangers and Mash";
    info1.appendChild(head1);
    const blurb1 = document.createElement("p");
    blurb1.textContent = "Three succulent sausage links served with mashed potatoes and gravy.";
    info1.appendChild(blurb1);
    const price1 = document.createElement("p");
    price1.textContent = "11S 20K";
    price1.classList.add("price");
    info1.appendChild(price1);
    main.appendChild(card1);

    const card2 = document.createElement("div");
    const info2 = document.createElement("div");
    card2.classList.add("card");
    info2.classList.add("info");
    const image2 = document.createElement("img");
    image2.src = kidney;
    image2.classList.add("menu-img");
    image2.setAttribute("alt", "Picture of steak and kidney pie");
    card2.appendChild(image2);
    card2.appendChild(info2);
    const head2 = document.createElement("h3");
    head2.textContent = "Steak and Kidney Pie";
    info2.appendChild(head2);
    const blurb2 = document.createElement("p");
    blurb2.textContent = "Our flaky pastry crust filled with beef, kidney, onion, carrot, mushroom, and a rich gravy.";
    info2.appendChild(blurb2);
    const price2 = document.createElement("p");
    price2.textContent = "13S 12K";
    price2.classList.add("price");
    info2.appendChild(price2);
    main.appendChild(card2);

    const card3 = document.createElement("div");
    const info3 = document.createElement("div");
    card3.classList.add("card");
    info3.classList.add("info");
    const image3 = document.createElement("img");
    image3.src = pea;
    image3.classList.add("menu-img");
    image3.setAttribute("alt", "Picture of pea soup");
    card3.appendChild(image3);
    card3.appendChild(info3);
    const head3 = document.createElement("h3");
    head3.textContent = "Pea Soup";
    info3.appendChild(head3);
    const blurb3 = document.createElement("p");
    blurb3.textContent = "A house favorite, our pea soup is rich and perfect to accompany another dish, or to enjoy on its own.";
    info3.appendChild(blurb3);
    const price3 = document.createElement("p");
    price3.textContent = "9S 8K";
    price3.classList.add("price");
    info3.appendChild(price3);
    main.appendChild(card3);

    const card4 = document.createElement("div");
    const info4 = document.createElement("div");
    card4.classList.add("card");
    info4.classList.add("info");
    const image4 = document.createElement("img");
    image4.src = yorkshire;
    image4.classList.add("menu-img");
    image4.setAttribute("alt", "Picture of yorkshire pudding");
    card4.appendChild(image4);
    card4.appendChild(info4);
    const head4 = document.createElement("h3");
    head4.textContent = "Yorkshire Pudding";
    info4.appendChild(head4);
    const blurb4 = document.createElement("p");
    blurb4.textContent = "A delectable pastry topped with roast beef and gravy, and served with grilled seasonal vegetables.";
    info4.appendChild(blurb4);
    const price4 = document.createElement("p");
    price4.textContent = "14S";
    price4.classList.add("price");
    info4.appendChild(price4);
    main.appendChild(card4);

    const card5 = document.createElement("div");
    const info5 = document.createElement("div");
    card5.classList.add("card");
    info5.classList.add("info");
    const image5 = document.createElement("img");
    image5.src = shepherd;
    image5.classList.add("menu-img");
    image5.setAttribute("alt", "Picture of shepherds pie");
    card5.appendChild(image5);
    card5.appendChild(info5);
    const head5 = document.createElement("h3");
    head5.textContent = "Shepherds Pie";
    info5.appendChild(head5);
    const blurb5 = document.createElement("p");
    blurb5.textContent = "Minced lamb, gravy, and vegetables, topped with mashed potatoes. Serves two.";
    info5.appendChild(blurb5);
    const price5 = document.createElement("p");
    price5.textContent = "1G";
    price5.classList.add("price");
    info5.appendChild(price5);
    main.appendChild(card5);

    const card6 = document.createElement("div");
    const info6 = document.createElement("div");
    card6.classList.add("card");
    info6.classList.add("info");
    const image6 = document.createElement("img");
    image6.src = toad;
    image6.classList.add("menu-img");
    image6.setAttribute("alt", "Picture of toad in the hole");
    card6.appendChild(image6);
    card6.appendChild(info6);
    const head6 = document.createElement("h3");
    head6.textContent = "Toad in the Hole";
    info6.appendChild(head6);
    const blurb6 = document.createElement("p");
    blurb6.textContent = "Our Yorkshire pudding pastry with sausages, garnished with onion gravy and parsley.";
    info6.appendChild(blurb6);
    const price6 = document.createElement("p");
    price6.textContent = "10S 7K";
    price6.classList.add("price");
    info6.appendChild(price6);
    main.appendChild(card6);

    const mainmenu = document.createElement("button");
    mainmenu.textContent = "Main Menu";
    mainmenu.classList.add("mainmenu");
    mainmenu.addEventListener("click", () => {
      loadMenu();
    })
    main.appendChild(mainmenu);
  }